root = "."
tmp_dir = "tmp"

[build]
  bin = "./dist/vibefeeder"
  cmd = "go build -o ./dist/vibefeeder ./cmd/vibefeeder"
  pre_cmd = ["templ generate"]
  exclude_dir = ["tmp", "node_modules", "dist"]
  exclude_regex = ["_test.go", "_templ.go"]
  include_ext = ["go", "templ"]
