name: Master Build & Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      run_e2e: false
    secrets: inherit

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup

      - name: Build Docker image
        run: task docker:build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker push ghcr.io/tjanas94/vibefeeder:${GIT_SHA}

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - uses: actions/checkout@v5

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          flyctl deploy --ha=false --image ghcr.io/tjanas94/vibefeeder:${GIT_SHA}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
